### ISSUE TITLE
S3File whitelist says that it is blank even if it isn't

### ISSUE THREAD

**Issue by perlDreamer** [plainblack/TGCv#8]
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'includes')
  at S3FileRecord.verifyExtension (./ving/record/records/S3File.mjs:224:24)  
  at Object.handler (./server/api/v1/hardwareticketfile/[id]/import-s3file.put.mjs:18:18)

**Comment by rizen** [comment]
fixed
